openapi: 3.0.0
info:
  version: '1.0.0'
  title: 'Library API'
  description: 'This API is used for Library'
  termsOfService: www.ibm.com
  contact:
    name: Bill
    url: www.ibm.com
    email: wleonar@us.ibm.com
  license:
    name: IBM license
    url: www.ibm.com

paths:
  /library/book/{isbn}:
    get:
      summary: Get a book
      description: Get a book
      parameters:
        - name: isbn
          in: path
          description: Book info
          required: true
          schema:
            type: string
      responses:
        200:
          description: successful
          content:
            application/json:
              schema:
                type: object
                items:
                  properties:
                    bookType:
                      type: string
                      example: FICTION
                    isbn:
                      type: string
                      example: 12345
                    title:
                      type: string
                      example: Some Book
                    author:
                      type: string
                      example: Tom Smith

servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/IBM8373/EMP_API_OAS3.0/1.0.0
