apiVersion: v1
kind: Service
metadata:
  name: bookinventoryservice
spec:
  type: NodePort
  selector:
    app: bookinventory
  ports:
    - protocol: TCP
      nodePort: 30082
      port: 9002
      targetPort: 9002